#image: fedora:latest
#image: redhat:latest
pages:
  image: fedora:latest
  image: alpine:latest
  stage: deploy
  script:
    - echo 'Deploying to GitLab Pages...'
    - mkdir .public
    - cp -r /client/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
  except:
    - schedules
    - triggers
  when: on_success
  allow_failure: false
  environment:
    name: production
    url: https://www.krafi.info/

rollback:
  stage: deploy
  script:
    - echo 'Rolling back to last successful version...'
    - git reset --hard HEAD^
    - git push --force
  when: on_failure
  needs: [pages]

before_script:
  - cp client-side.html index.html
